#!/bin/bash

# All credits to: https://blog.jdriven.com/2020/11/formatting-in-pre-commit-hook/
set -e

# command taken from https://github.com/JLLeitschuh/ktlint-gradle  task addKtlintFormatGitPreCommitHook
filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.scala|\.java|\.md/ { print $2}')"

echo "Files to format: $filesToFormat"
for sourceFilePath in $filesToFormat

do
  ./gradlew spotlessApply -PspotlessIdeHook="$(pwd)/$sourceFilePath"
  git add $sourceFilePath
done;